-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES AS BS
JOIN
    BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
JOIN
    AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE
    BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    B.AUTHOR_ID,
    B.CATEGORY
ORDER BY
    B.AUTHOR_ID ASC,
    B.CATEGORY DESC;