-- 코드를 작성해주세요
SELECT
    CASE
        -- frontend & python
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) AND (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python')) THEN 'A'
        -- c#
        WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) THEN 'B'     
        -- else
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End')) THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM
    DEVELOPERS
HAVING
    GRADE IS NOT NULL
ORDER BY
    GRADE ASC, ID ASC